import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ChevronDown, Menu, X, Check, Sparkles, ExternalLink } from 'lucide-react';
import './styles.css';

const signup = 'https://bxup9uklfcb.feishu.cn/share/base/form/shrcnWUMlgpbwHaXgzV7HmNhNhg';
const nav = [['赛程','schedule'],['奖励','rewards'],['方向','tracks'],['验收标准','criteria'],['常见问题','faq']];

function App(){
 const [open,setOpen]=useState(false); const [faq,setFaq]=useState(0); const [sample,setSample]=useState('MoonBit makes tools\\nTools should be small and useful'); const words=sample.trim()?sample.trim().split(/\\s+/).length:0; const lines=sample?sample.split('\\n').length:0; const chars=sample.length;
 return <div className="app">
  <header className="top"><div className="wrap navwrap"><a className="brand" href="#top"><span className="brandmark">M</span><span>MoonBit <b>Hackathon</b></span></a><nav>{nav.map(([n,id])=><a href={'#'+id} key={id}>{n}</a>)}</nav><a className="navcta" href={signup} target="_blank">立即报名 <ArrowUpRight size={16}/></a><button className="menubtn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobilemenu">{nav.map(([n,id])=><a onClick={()=>setOpen(false)} href={'#'+id} key={id}>{n}</a>)}<a className="mobilecta" href={signup}>立即报名 <ArrowUpRight size={15}/></a></div>}</header>
  <main id="top">
   <section className="hero"><div className="gridglow"></div><div className="wrap hero-inner"><div className="eyebrow"><span className="dot"></span> 2026 · 九月赛进行中</div><h1>从一个清晰的目标<br/><em>走到可验收的成果。</em></h1><p className="lead">用 MoonBit 与 AI，把真实需求做成开源软件。<br/>公开开发、持续提交，完成你的一个月创造。</p><div className="hero-actions"><a className="primary" href={signup} target="_blank">提交项目申报 <ArrowUpRight size={18}/></a><a className="secondary" href="#schedule">了解赛程 <span>↓</span></a></div><div className="hero-meta"><span><strong>9.30</strong> 报名与验收截止</span><span className="sep">/</span><span>单人最高约 <strong>¥75,000</strong></span></div></div><div className="hero-orbit orbit1"></div><div className="hero-orbit orbit2"></div><div className="hero-card"><span className="card-label">THIS MONTH</span><strong>SEPTEMBER</strong><div className="card-line"><span>OPEN CALL</span><span>01—30</span></div><div className="card-bar"><i></i></div><small>Build in public · Ship for real</small></div></section>
   <section className="ticker"><div className="ticker-track"><span>BUILD IN PUBLIC</span><b>✦</b><span>MOONBIT + AI</span><b>✦</b><span>REAL PROBLEMS, OPEN SOURCE</span><b>✦</b><span>BUILD IN PUBLIC</span><b>✦</b><span>MOONBIT + AI</span><b>✦</b></div></section>
   <section className="section schedule" id="schedule"><div className="wrap"><div className="section-head"><div><span className="kicker">01 / TIMELINE</span><h2>每一步，都有<br/><em>清晰的下一步。</em></h2></div><p>赛程在线完成。围绕公开仓库推进，让开发过程和最终质量都可追踪。</p></div><div className="timeline">{[['01','报名申报','报名开放后','提交参赛信息、公开仓库与一页项目说明。'],['02','资格审核','滚动审核','确认选题、工作范围与参赛信息，通过后进入本期开发。'],['03','集中开发','9 月第一周—30 日','公开持续提交，保留 Issues、PR 与更新记录。'],['04','项目验收','9 月 30 日','提交代码、README、测试与可复现的演示说明。'],['05','季度评选','每季度统一评选','汇总当季度已通过验收的新项目与社区维护项目。']].map((x,i)=><div className={'timeitem '+(i===2?'active':'')} key={x[0]}><div className="time-num">{x[0]}</div><div><h3>{x[1]} {i===2&&<span className="live">进行中</span>}</h3><div className="time-date">{x[2]}</div><p>{x[3]}</p></div></div>)}</div></div></section>
   <section className="section dark rewards" id="rewards"><div className="wrap"><div className="section-head light"><div><span className="kicker">02 / REWARDS</span><h2>多周期奖金，<br/><em>可以叠加。</em></h2></div><p>月度支持、季度、半年度与年度奖金分别评定，互不冲突。</p></div><div className="reward-grid"><div className="reward-card featured"><span>MONTHLY SUPPORT</span><strong><small>¥</small>500</strong><p>启动支持 + 完成支持</p><div className="split"><span>启动 <b>¥150</b></span><span>完成 <b>¥350</b></span></div></div>{[['季度一等奖','¥12,000','一等奖 1–2 名'],['半年度一等奖','¥24,000','上半年度评选'],['年度一等奖','¥36,000','年度最高荣誉']].map(x=><div className="reward-card" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><p>{x[2]}</p><div className="plus">＋</div></div>)}</div><div className="reward-note"><Sparkles size={16}/> 奖金分别评定，互不冲突，单人最高可获约 7.5 万元</div></div></section>
   <section className="section tracks" id="tracks"><div className="wrap"><div className="section-head"><div><span className="kicker">03 / DIRECTIONS</span><h2>从基础软件出发，<br/><em>解决一个真实问题。</em></h2></div><p>以下方向用于启发选题，不构成限制。原创项目与成熟生态库的 MoonBit 移植均可参与。</p></div><div className="track-grid">{[['01','工具库','通用工具库、协议库与可复用的基础组件。','✣'],['02','数据处理','数据处理、数据库、分析与内容处理工具。','◫'],['03','AI 应用','结合 AI 能力，解决真实需求的开源应用。','✦'],['04','开发者工具','解释器、运行时、LSP、CLI 与开发体验工具。','⌘']].map(x=><article className="track" key={x[0]}><span className="track-no">{x[0]}</span><div className="track-icon">{x[3]}</div><h3>{x[1]}</h3><p>{x[2]}</p><a href={signup}>选择这个方向 <ArrowUpRight size={15}/></a></article>)}</div></div></section>
   <section className="section criteria" id="criteria"><div className="wrap"><div className="criteria-inner"><div><span className="kicker">04 / ACCEPTANCE</span><h2>验收看得见，<br/><em>也跑得起来。</em></h2><a className="outline" href={signup}>查看申报表单 <ExternalLink size={16}/></a></div><div className="checks">{[['MoonBit 为主','以 MoonBit 作为项目主要实现语言。'],['仓库公开','保留连续、可追踪的提交与开发记录。'],['能够运行','提供清晰 README、可运行示例与必要测试。'],['工作有效','已有项目必须包含本期完成的实质新增工作。'],['开源合规','使用认可的开源许可证，并说明移植或参考来源。'],['AI 可解释','可以使用 AI 辅助，但目标、路径与质量由参赛者掌握。']].map(x=><div className="check" key={x[0]}><span><Check size={15}/></span><div><h3>{x[0]}</h3><p>{x[1]}</p></div></div>)}</div></div></div></section>
   <section className="section faq" id="faq"><div className="wrap narrow"><div className="section-head"><div><span className="kicker">05 / FAQ</span><h2>开始之前，<br/><em>先确认这些。</em></h2></div></div><div className="faq-list">{[['什么项目适合参加？','优先选择边界清晰、能够在一个月内交付并验证的项目。原创项目、成熟生态库的 MoonBit 移植，以及持续维护的社区项目均可参与。'],['已有项目可以参加吗？','可以。已有项目必须包含本期完成的实质新增工作；移植项目需要说明来源与许可证。'],['开发过程需要公开到什么程度？','请在公开仓库持续提交，并保留 commits、Issues、PR 与更新记录，确保过程可追踪。'],['什么时候截止？','本期九月赛在 9 月 30 日截止报名与项目验收。']].map((x,i)=><div className={'faqitem '+(faq===i?'open':'')} key={x[0]}><button onClick={()=>setFaq(faq===i?-1:i)}><span>{x[0]}</span><ChevronDown size={20}/></button>{faq===i&&<p>{x[1]}</p>}</div>)}</div></div></section>
   <section className="section demo" id="demo"><div className="wrap"><div className="section-head"><div><span className="kicker">LIVE DEMO / MOONPULSE</span><h2>先看见数据，<br/><em>再做决定。</em></h2></div><p>MoonPulse 是本期项目的 MoonBit 核心功能：粘贴一段文本，立即得到可复现的基础统计。</p></div><div className="demo-box"><textarea value={sample} onChange={e=>setSample(e.target.value)} aria-label="输入待分析文本"/><div className="demo-results"><div><b>{lines}</b><span>行</span></div><div><b>{words}</b><span>词</span></div><div><b>{chars}</b><span>字符</span></div></div><div className="demo-caption"><span>MoonBit text analytics · zero dependencies</span><a href="https://github.com/moonbitlang" target="_blank">查看源码 <ArrowUpRight size={14}/></a></div></div></div></section>   <section className="final-cta"><div className="wrap"><span className="kicker">READY TO BUILD?</span><h2>把你的想法，<br/><em>交付出来。</em></h2><a className="primary" href={signup} target="_blank">立即报名参赛 <ArrowUpRight size={18}/></a><p>报名需提交参赛信息、公开仓库与一页项目说明。</p></div></section>
  </main><footer><div className="wrap foot"><div className="brand"><span className="brandmark">M</span><span>MoonBit <b>Hackathon</b></span></div><span>2026 · Build in public, ship for real.</span><a href="https://github.com/moonbitlang" target="_blank"><span className="github-mark">GH</span></a></div></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);


